### ISSUE TITLE
disappeared entity

### ISSUE THREAD

**Issue by MisteurJ** [RomeHein/homeassistant_enocean#5]
Hi,

I was using this nice integration for several years, until a week ago, where without touching anything, the entity for my Enocean temp sensor disappeared...
I did not touch the config file.
My two others sensors work great, but no more available temp sensor entity. I tried to delete it, but I can't make it appear anymore...
Could it be related with an update of HA ?

Thank you !!

```
sensor:
  - name: temperature_exterieure
    platform: enocean
    id: [0x05,0x05,0xEE,0x11]
    device_class: temperature
    min_temp: -30
    max_temp: 50

binary_sensor:
  - name: porte_entree
    platform: enocean
    id: [0x05,0x04,0x1E,0xCF]
    device_class: door

  - name: fenetre_salon_so
    platform: enocean
    id: [0x05,0x11,0x5D,0x2C]
    device_class: door
```
